# Markdownlint configuration for SparseTagging
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Enable all rules by default
default: true

# MD013: Line length
# Disabled because technical documentation often has long lines (code blocks, links, tables)
MD013: false

# MD033: Inline HTML
# Disabled to allow HTML in markdown (useful for complex tables, badges, etc.)
MD033: false

# MD034: Bare URLs
# Disabled to allow bare URLs in documentation (common in technical docs)
MD034: false

# MD041: First line in file should be a top-level heading
# Disabled because some files start with front matter or badges
MD041: false

# MD024: Multiple headings with the same content
# Only check siblings to allow same heading text in different sections
MD024:
  siblings_only: true

# Ignore patterns for directories that shouldn't be linted
ignore:
  - "ScanResults/**"
  - "node_modules/**"
  - ".venv/**"
  - "**/.venv/**"
